In [ ]:
import pandas as pd

In [6]:
df = pd.read_csv('../data/raw/insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [7]:
def describe_df(df):
    descriptive_summary = df.describe(include="all").T
    descriptive_summary["n_unique"] = df.nunique()
    descriptive_summary["null_count"] = df.isnull().sum()
    descriptive_summary["skewness"] = df.skew(numeric_only=True)
    descriptive_summary["kurtosis"] = df.kurtosis(numeric_only=True)
    descriptive_summary["type"] = df.dtypes
    
    try:
        descriptive_summary = descriptive_summary.drop(columns=["unique", "top", "freq"])
    except:
        pass

    return descriptive_summary

In [8]:
descriptive_summary = describe_df(df)
descriptive_summary

,count,mean,std,min,25%,50%,75%,max,n_unique,null_count,skewness,kurtosis,type
age,1338.0,39.207025,14.04996,18.0,27.0,39.0,51.0,64.0,47,0,0.055673,-1.245088,int64
sex,1338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,NaN,NaN,object
bmi,1338.0,30.663397,6.098187,15.96,26.29625,30.4,34.69375,53.13,548,0,0.284047,-0.050732,float64
children,1338.0,1.094918,1.205493,0.0,0.0,1.0,2.0,5.0,6,0,0.938380,0.202454,int64
smoker,1338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,NaN,NaN,object
region,1338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0,NaN,NaN,object
charges,1338.0,13270.422265,12110.011237,1121.8739,4740.28715,9382.033,16639.912515,63770.42801,1337,0,1.515880,1.606299,float64

In [9]:
df = df.dropna()
df = df.drop_duplicates()

df["smoker"] = df["smoker"].map({'yes': 1, 'no': 0})
df["sex"] = df["sex"].map({'male': 1, 'female': 0})
df = df.drop(columns=["region"])
df.head()

   age  sex     bmi  children  smoker      charges
0   19    0  27.900         0       1  16884.92400
1   18    1  33.770         1       0   1725.55230
2   28    1  33.000         3       0   4449.46200
3   33    1  22.705         0       0  21984.47061
4   32    1  28.880         0       0   3866.85520

In [10]:
descriptive_summary = describe_df(df)
descriptive_summary

,count,mean,std,min,25%,50%,75%,max,n_unique,null_count,skewness,kurtosis,type
age,1337.0,39.222139,14.044333,18.0000,27.000,39.0000,51.00000,64.00000,47,0,0.054781,-1.244406,int64
sex,1337.0,0.504862,0.500163,0.0000,0.000,1.0000,1.00000,1.00000,2,0,-0.019469,-2.002619,int64
bmi,1337.0,30.663452,6.100468,15.9600,26.290,30.4000,34.70000,53.13000,548,0,0.283914,-0.052947,float64
children,1337.0,1.095737,1.205571,0.0000,0.000,1.0000,2.00000,5.00000,6,0,0.937421,0.200954,int64
smoker,1337.0,0.204936,0.403806,0.0000,0.000,0.0000,0.00000,1.00000,2,0,1.463601,0.142339,int64
charges,1337.0,13279.121487,12110.359656,1121.8739,4746.344,9386.1613,16657.71745,63770.42801,1337,0,1.515391,1.604221,float64

In [12]:
df.to_csv('../data/processed/cleaned_insurance.csv')